title: AgileSites3
subtitle: "AgileSites3 the development tool  for agile development with WebCenter Sites 12c"
description: "AgileSites3 the development tool for agile development with WebCenter Sites 12c"
author: Michele Sciabarra
language: en
timezone: UTC
url: https://www.agile4sites.com
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy

google_analytics: UA-10041673-6
twitter: AgileSitesFw

deploy:
  type: s3
  bucket: www.agile4sites.com
  aws_key: AKIAIL4QNWCQ5QWEJ4VQ
  aws_secret: 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
