<%-- DO NOT EDIT - GENERATED BY AgileSites
--%><%@ page autoFlush="true" buffer="1024kb"
             import="COM.FutureTense.Interfaces.FTValList"
%><%@ taglib prefix="cs" uri="futuretense_cs/ftcs1_0.tld"
%><%@ taglib prefix="ics" uri="futuretense_cs/ics.tld"
%><%@ taglib prefix="asset" uri="futuretense_cs/asset.tld"
%><cs:ftcs><%
String jar = ics.GetVar("jar");
if(jar!=null) {
   byte[] bytes = org.apache.commons.io.IOUtils.toByteArray(application.getResourceAsStream(jar));
   System.out.println(bytes.length);
   String file = new String(org.apache.commons.codec.binary.Base64.encodeBase64(bytes));
   ics.StreamText("\"");
   ics.StreamText(file);
   ics.StreamText("\"");
   System.out.println("sent");
} else {
%>{"info":[<%
String[] types = new String[]{ "CSElement", "SiteEntry" };
for(String type: types) {
%>
<asset:list type='<%=type%>'  list='<%=type%>'/>
<ics:listloop listname='<%=type%>'>
    <ics:listget listname='<%=type%>' fieldname="name" output="name"/>
    <ics:listget listname='<%=type%>' fieldname="id" output="id"/>
<%
    String name = ics.GetVar("name");
    String id = ics.GetVar("id");
    if(name.startsWith("AAAgile")) {
%>{ "type": "<%= type%>",
    "name": "<%= name%>" ,
    "id": "<%= id%>"
},<% } %>
</ics:listloop>
<% } %>{
    "type": "Info",
    "name": "sites.version",
    "id": "<%= ics.GetProperty("ft.version") %>"
},{
   "type": "Info",
   "name": "agilesites.version",
   "id": "299001"
}]}
<% } %>
</cs:ftcs>